brpartners/web/Controllers/FinancialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using QX3.Portal.Contracts.DataContracts;
using QX3.Portal.WebSite.CommonService;
using QX3.Portal.WebSite.FinancialService;
using QX3.Portal.WebSite.Helper;
using QX3.Portal.WebSite.LogService;
using QX3.Portal.WebSite.Models;
using QX3.Portal.WebSite.Models.Channel;
using QX3.Portal.WebSite.Properties;
using QX3.Spinnex.Common.Services.Logging;

namespace QX3.Portal.WebSite.Controllers
{
    public class FinancialController : FileController
    {
        #region Projected Report

        [AccessControlAuthorize]
        public ActionResult ProjectedReport()
        {
            return View();
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public void LoadProjectedReport(string Assessors, string Clients, char Type, string TradingDate, string SettleDate)
        {
            try
            {
                LogHelper.SaveAuditingLog("Financial.LoadProjectedReport");

                MarketHelper helper = new MarketHelper();

                ProjectedReportFilter filter = new ProjectedReportFilter();
                filter.Assessors = String.IsNullOrEmpty(Assessors) ? "" : helper.GetAssessorsRangesToFilter(Assessors);
                if (!string.IsNullOrEmpty(Clients))
                    filter.Clients = helper.GetClientsRangesToFilter(Clients);
                filter.TradingDate = TradingDate;
                filter.SettlementDate = SettleDate;
                filter.Type = Type;

                IChannelProvider<IFinancialContractChannel> channelProvider = ChannelProviderFactory<IFinancialContractChannel>.Create("FinancialClassName");
                var service = channelProvider.GetChannel().CreateChannel();

                service.Open();

                var report = service.LoadProjectedReport(filter, CommonHelper.GetLoggedUserGroupId()).Result;

                Session["Financial.ProjectedReport"] = report == null ? new List<ProjectedReportItem>() : report.ToList();

                LogHelper.SaveAuditingLog("Proceeds.LoadProceeds", string.Format(LogResources.AuditingLoadProceeds, JsonConvert.SerializeObject(filter), JsonConvert.SerializeObject(Session["Proceeds"])));

                service.Close();

            }
            catch (Exception ex)
            {
                LogManager.WriteError(ex);
            }
        }

        public ActionResult ConfirmProjectedExport()
        {
            return View();
        }

        public ActionResult ProjectedReportToFile(string exportType, string groupBy)
        {
            List<ProjectedReportItem> currentList = new List<ProjectedReportItem>();
            bool exportToPdf = exportType == "PDF";
            try
            {
                if (Session["Financial.ProjectedReport"] != null)
                    currentList = (List<ProjectedReportItem>)Session["Financial.ProjectedReport"];

                //LogHelper.SaveAuditingLog("Financial.ProjectedReportToFile", string.Format(LogResources.ObjectToFileParameters, exportToPdf ? "PDF" : "Excel", JsonConvert.SerializeObject(currentList)));

                string fileName = string.Format("projetado_{0}.{1}", DateTime.Now.ToString("dd-MM-yyyy"), exportToPdf ? "pdf" : "xls");

                LogHelper.SaveHistoryLog("Financial.ProjectedReport", new HistoryData { Action = "Exportar", OldData = string.Empty, NewData = JsonConvert.SerializeObject(currentList) });

                return ViewProjectedReportToFile(currentList, true, fileName, groupBy, exportToPdf);
            }
            catch (Exception ex)
            {
                LogManager.WriteError(ex);
                TempData["ErrorMessage"] = Resources.GenericReportErrorMessage;
                return this.RedirectToAction("ProjectedReport");
            }
        }

        #endregion

		#region Redemption Request

        [AccessControlAuthorize]
        public ActionResult RedemptionRequest()
        {
            string statusID = null;

            ViewBag.Status = new SelectList(this.LoadRedemptionRequestStatus(), "value", "description", statusID);
            ViewBag.Pending = this.LoadPendingRequests();

            return View();
        }

        public ActionResult RedemptionRequestItemsToFile(bool isPdf)
        {
            List<RedemptionRequestListItem> currentList = new List<RedemptionRequestListItem>();
            try
            {
				if (Session["RedemptionRequest.List"] != null)
					currentList = (List<RedemptionRequestListItem>)Session["RedemptionRequest.List"];

                string fileName = string.Format("solicitacaoresgate_{0}.{1}", DateTime.Now.ToString("dd-MM-yyyy"), isPdf ? "pdf" : "xls");

                LogHelper.SaveHistoryLog("Financial.RedemptionRequest", new HistoryData { Action = "Exportar", OldData = string.Empty, NewData = JsonConvert.SerializeObject(currentList) });

                return isPdf ? ViewRedemptionRequestItemsPdf(currentList, true, fileName) : ViewRedemptionRequestItemsExcel(currentList, true, fileName);
            }
            catch (Exception ex)
            {
                LogManager.WriteError(ex);
                TempData["ErrorMessage"] = "Ocorreu um erro ao gerar relatório.";
                return this.RedirectToAction("RedemptionRequest");
            }


        }

        private List<CommonType> LoadRedemptionRequestStatus()
        {
            try
            {
                List<CommonType> lst = (List<CommonType>)Session["RedemptionRequest.Status"];

                if (lst == null)
                {
                    lst = new List<CommonType>();
                    lst.Add(new CommonType { Value = "", Description = "Todos" });

                    IChannelProvider<ICommonContractChannel> channelProvider = ChannelProviderFactory<ICommonContractChannel>.Create("CommonClassName");
                    var service = channelProvider.GetChannel().CreateChannel();

                    service.Open();
                    var result = service.LoadTypes("Financial.RedemptionRequest", "status").Result;
                    service.Close();

                    if (result != null && result.Count() > 0)
                        lst.AddRange(result.ToList());

                    Session["RedemptionRequest.Status"] = lst;
                }

                return lst;
            }
            catch (Exception)
            {
                List<CommonType> lst = new List<CommonType>();
                lst.Add(new CommonType { Value = "", Description = "Todos" });
                return lst;
            }
        }

        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public void LoadRedemptionRequests(string assessors, string clients, string status, string startDate, string endDate)
        {
            try
            {
                LogHelper.SaveAuditingLog("Financial.LoadRedemptionRequests");

                RedemptionRequestFilter filter = new RedemptionRequestFilter();

                MarketHelper helper = new MarketHelper();
                filter.Assessors = String.IsNullOrEmpty(assessors) ? "" : helper.GetAssessorsRangesToFilter(assessors);
                if (!string.IsNullOrEmpty(clients))
                    filter.Clients = helper.GetClientsRangesToFilter(clients);

                filter.StatusID = string.IsNullOrEmpty(status) ? 0 : Convert.ToInt32(status);

                if (!string.IsNullOrEmpty(startDate))
                    filter.StartDate = startDate;

                if (!string.IsNullOrEmpty(endDate))
                    filter.EndDate = endDate;

                IChannelProvider<IFinancialContractChannel> financialProvider = ChannelProviderFactory<IFinancialContractChannel>.Create("FinancialClassName");
                var service = financialProvider.GetChannel().CreateChannel();

                service.Open();

                var list = service.LoadRedemptionRequest(filter, CommonHelper.GetLoggedUserGroupId()).Result;

                service.Close();

                int index = 0;
                Session["RedemptionRequest.List"] = (from t in list
                                                     select new RedemptionRequestListItem
                                                     {
                                                         Id = t.ID.ToString(),
                                                         RequestedDate = t.RequestDate.ToString("dd/MM/yyyy HH:mm"),
                                                         ClientName = t.Client.Description,
                                                         ClientCode = t.Client.Value,
                                                         Bank = string.Format("{0} - {1}", t.BankAccount.BankCode, t.BankAccount.BankName),
                                                         Agency = string.Format("{0}{1}", t.BankAccount.AgencyNumber.ToString(), string.IsNullOrEmpty(t.BankAccount.AgencyDigit) ? "" : "-" + t.BankAccount.AgencyDigit),
                                                         Account = string.Format("{0}{1}", t.BankAccount.AccountNumber.ToString(), string.IsNullOrEmpty(t.BankAccount.AccountDigit) ? "" : "-" + t.BankAccount.AccountDigit),
                                                         Amount = t.RedemptionValue.ToString("N2"),
                                                         StatusId = t.Status.Value,
                                                         StatusDescription = t.Status.Description,
                                                         Observation = t.Observation,
                                                         Index = index++
                                                     }).ToList();

            }
            catch (Exception ex)
            {
                LogManager.WriteError(ex);
            }
        }

        public ActionResult RedemptionRequestEdit(string id)
        {

brpartners/web/Views/Financial/ConfirmProjectedExport.cshtml
@{
    Layout = null;
}
@using (Html.BeginForm("ProjectedReportToFile", "Financial", FormMethod.Post, new { @Id = "frmConfirmExport" }))
{
    string reportType = Request["isPdf"] == "true" ? "PDF" : "Excel";
    @Html.Hidden("exportType", reportType);
    <h2>
        Exportar para @reportType</h2>
    <div class="conteudo" id="ConfirmArea">
        <div class="linha-frm">
            <strong>@Html.Label("Agrupar dados por:")</strong>
            <div class="lista-opcoes-vertical">
                @Html.RadioButton("groupBy", "A", true)
                <label>
                    Assessor</label>
                @Html.RadioButton("groupBy", "", false)
                <label>
                    Nenhum</label>
            </div>
        </div>
        <div class="linha-btn">
            <a type="button" class="btn-primario" href="#" name="btnExport" id="btnExport" title="exportar termos"
                onclick="$('#frmConfirmExport').submit();"><span>exportar relatório</span></a>
        </div>
        <span class="quebrar"></span>
    </div>
    <span class="quebrar"></span>
    
}

brpartners/web/Views/Financial/DailyFinancialReportFilter.cshtml
<script src="@Url.Content("~/Scripts/jQuery/ui/jquery-ui-1.8.16.custom.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Helpers/ValidateHelper.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Views/Financial/DailyFinancialReportFilter.js")" type="text/javascript"></script>

<div class="filtro-padrao">
    <div class="topo" id="DailyFinancialReportFilter">
		        Filtrar por
    </div>
    @using (Html.BeginForm())
    {
	<div class="conteudo" id="DailyFinancialReportContent" style="display:none;">
        <span class="quebrar"></span>
		<div class="linha-frm">
			<label>Assessor</label>
			@Html.TextBox("txtAssessorFilter")
		</div>
		<div class="linha-frm">
			<label>Cliente</label>
			@Html.TextBox("txtClientFilter")
		</div>
        <span class="quebrar"></span>
        <div class="linha-frm liquidacao">
            <div class="lista-opcoes-vertical">
			    <input type="checkbox" id="chkD0" name="chkD0" /> <label>Apenas com liquidação hoje</label>
            </div>
		</div>
		<div class="linha-frm">
			<label>Situação</label>
			<select id="ddlStatus" name="ddlStatus">
				<option value="T">Todos</option>
				<option value="P">Positivos</option>
				<option value="N">Negativos</option>
			</select>
		</div>
        <div class="linha-frm">
			<label>Taxa de Custódia</label>
			<select id="ddlCustody" name="ddlCustody">
				<option value="T">Todos</option>
				<option value="S">Sim</option>
				<option value="N">Não</option>
			</select>
		</div>
        <div class="linha-frm">
			<label>Data de Movimentação</label>
			@Html.TextBox("txtMovementDate", null, new { @maxlength = "10" })
		</div>
		<div class="linha-btn">
			<a class="btn-padrao" href="javascript:;" id="lnkSubmitFilter"><span>Listar Saldos</span></a>
		</div>
		<span class="quebrar"></span>
	</div>
    }
  </div>

brpartners/web/Views/Financial/RedemptionRequest.cshtml
@{
    ViewBag.Title = "Solicitação de Resgate";
   
}
<script src="@Url.Content("~/Scripts/jQuery/ui/jquery-ui-1.8.16.custom.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jQuery/meioMask/jquery.meio.mask.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jQuery/ui/jquery.ui.datepicker-pt-BR.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Helpers/ValidateHelper.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Helpers/DateHelper.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jQuery/dataTables/dataTables.BrDate.js")" type="text/javascript"></script>

<script src="@Url.Content("~/Scripts/jQuery/ui/jquery.maxlength.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Views/Financial/RedemptionRequest.js")" type="text/javascript"></script>
@{ var feedbackDisplay = (TempData["Success"] != null) ? "block" : "none";}
@using (Html.BeginForm())
{
    QX3.Portal.WebSite.Helper.AccessControlHelper acHelper = new QX3.Portal.WebSite.Helper.AccessControlHelper();
    
    <div id="divRedemptionRequestFeedback" class="sucesso-flutuante" style='display:none;'>
        <span></span><a href="#" class="lnk-fechar" onclick="$('#divRedemptionRequestFeedback').slideToggle();" id="closeFeedback">fechar</a>
    </div>
    
    <div class="ferramentas acoes assessores">
        @if (acHelper.HasFuncionalityPermission("Financial.RedemptionRequest", "btnRequest"))
        { <a class="btn-padrao" href="javascript:void(0);" onclick="OpenRequest(0);return false;"><span>Solicitar</span></a> }
        @if (acHelper.HasFuncionalityPermission("Financial.RedemptionRequest", "btnEffective"))
        { <a class="btn-secundario" href="javascript:void(0);" onclick="OpenEffect();return false;"><span>Efetuar</span></a> }
        @*<a class="btn-secundario" href="javascript:void(0);" id="btnApprove" ><span>Aprovar</span></a>*@
        <div>Exportar: <a id="lnkRedemptionRequestExcel" class="ico-xls" href="javascript:;">Excel</a>
        <a id="lnkRedemptionRequestPdf" class="ico-pdf" href="javascript:;">PDF</a>
            @if (acHelper.HasFuncionalityPermission("Financial.RedemptionRequest", "btnLog"))
             { <a class="ico-hist" href="javascript:void(0);" onclick="ViewHistory();return false;">Ver histórico</a> }
        </div>
    </div>
    @Html.Partial("RedemptionRequestFilter")
    <div id="feedbackError" class="erro" style='display:none;'>
    </div>
    
    <div id="emptyArea" class="sem-resultado" style="display: none;">
    </div>

    <div id="loadingArea" style="display: none; text-align: center;">
        <img src="../../img/preloadercinza.gif" alt="carregando consulta" />
    </div>

    <div class="area-resultado" id="tableArea" style="display: none;">
            <table cellspacing="0" width="100%" cellpadding="0" border="0" class="classificar" id="redemptionRequestList">
                <thead>
    	        <tr class="primario">
        	        <th rowspan="2" width="20px"><input type="checkbox" value="true" name="chkAll" id="chkAll" /></th>
        	        <th rowspan="2"><span>Solicitado em</span></th>
        	        <th rowspan="2" width="60px"><div style="width:60px;"><span>Código</span></div></th>
        	        <th rowspan="2" width="100px"><span>Cliente</span></th>
        	        <th colspan="3" class="agrupado" width="400px">Destino</th>
        	        <th rowspan="2"><span>Valor</span></th>
        	        <th rowspan="2"><span>Status</span></th>
        	        <th rowspan="2" width="69px"><div style="width:69px;">&nbsp;</div></th>
       	        </tr>
    	        <tr class="secundario">
        	        <th>Banco</th>
        	        <th>Agência</th>
        	        <th class="zerado">Conta</th>
       	        </tr>
            </thead>
                <tbody>
                </tbody>
            </table>
        
    </div>
}

<!-- MODAL DE SITUAÇÃO -->
<div class="modal-situacao" style="display: none;">
    <a onclick="Modal.Close();" class="closeLink" href="javascript:void(0);"><span>Fechar</span>
    </a>
    @using (Html.BeginForm("RedemptionRequestChangeStatus", "Financial", FormMethod.Post, new { @Id = "frmRedemptionRequestChangeStatus" }))
    {
        @Html.Hidden("hdCurrentStatus", "0")
		@Html.Hidden("hdId", "0")
		@Html.Hidden("hdClientCode", "0")
        <div class="linha-frm">
                <label>Alterar Status</label>
                <div class="erro" id="feedbackStatus" style="display: none;">Status inválido.</div>
                @Html.DropDownList("ddlStatusChange", (SelectList)ViewBag.Status, "--Selecione--", new { id = "ddlStatusChange" })
            </div>
            <div class="linha-frm">
                <label id="lbDisapproveNote" for="taDisapproveNote">Nota de reprovação</label>
			    @Html.TextArea("taDisapproveNote", new { style = "display: none; width: 187px" })
            </div>
        <div class="linha-btn">
            <a type="button" class="btn-padrao" href="javascript:void(0);" name="btnSettle" id="btnSettle" title="alterar status"
                onclick="ValidateSettle()"><span>Alterar Situação</span></a>
        </div>
	}
</div>

@if (ViewBag.Pending != null && ViewBag.Pending > 0)
{
    <div id="pendingTag" class="aviso" style="display: none;">
        <span><strong>@ViewBag.Pending</strong> Pendente@(ViewBag.Pending > 1 ? "s" : "")</span></div>
}

brpartners/web/Views/Financial/RedemptionRequestApprove.cshtml
@{
    Layout = null;
}
@using QX3.Portal.Contracts.DataContracts
@using QX3.Portal.WebSite.Helper
@using QX3.Portal.WebSite.Models

<script src="@Url.Content("~/Scripts/jQuery/ui/jquery-ui-1.8.16.custom.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Views/Financial/RedemptionRequestEffect.js?new=" + DateTime.Now.Ticks.ToString())" type="text/javascript"></script>

@using (Html.BeginForm("ConfirmRedemptionRequestApprove", "Financial", FormMethod.Post, new { @id = "frmRedemptionRequestApprove" }))
{   
    @Html.Hidden("hdfIds","")
    var total = string.Empty;
    var lstToValidate = (List<RedemptionRequestListItem>)ViewBag.RequestToValidate;
    if (lstToValidate != null && lstToValidate.Count > 0)
    {
       total = lstToValidate.Count.ToString();
       foreach (RedemptionRequestListItem item in lstToValidate)
       {
            <div class="conteudo confirmar-resgate" id="divConfirm-@item.Index" style="display:@(item.Index.Equals(1) ? "block" : "none");">
            <div class="alerta">O resgate irá gerar dívida no saldo projetado do cliente <br />@item.ClientCode - @item.ClientName.</div>
            <table cellpadding="0" cellspacing="0" class="classificar">
                <tbody>
                    <tr>
                        <td>Valor a Resgatar</td>
                        <td>@item.Amount</td>
                    </tr>
                    <tr>
                        <td>Saldo D0</td>
                        <td>@item.Balance.Available</td>
                    </tr>
                    <tr>
                        <td>Saldo Projetado</td>
                        <td>@item.Balance.Intended.Split('#')[0]</td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <td>Saldo após Resgate</td>
                        <td class="negativo">@item.Balance.Intended.Split('#')[1]</td>
                    </tr>
                </tfoot>
            </table>
        
        <div class="linha-btn">
            <a href="javascript:void(0);" class="btn-padrao" onclick="Next(@item.Index);"><span>Sim, resgatar mesmo assim</span></a>
            <a href="javascript:void(0);" class="btn-secundario" onclick="Cancel(@item.Index,@item.Id);"><span>Não resgatar</span></a>
        </div>

        </div>
        }
    } 
    else 
    {
        <div class="conteudo confirmar-resgate">
            <div class="alerta">Confirma a efetuação do resgate?</div>
            <div class="linha-btn">
                <a href="javascript:void(0);" class="btn-padrao" onclick="Next(-1);"><span>Sim, resgatar</span></a>
                <a href="javascript:void(0);" class="btn-secundario" onclick="Cancel(-1);"><span>Não resgatar</span></a>
            </div>
        </div>
    }
    @Html.Hidden("hdfTotal", total)
    
}

brpartners/web/Views/Financial/RedemptionRequestConfirmDelete.cshtml
@{
	Layout = null;
}
<h2>Deseja realmente excluir essa solictação?</h2>
<div id="ConfirmArea" class="conteudo">
	@using (Html.BeginForm("DeleteRedemptionRequest", "Financial", FormMethod.Post, new { @Id = "frmConfirmDelete" }))
     {
		    @Html.Hidden("hdfRequestId", Request["requestId"]);
            @Html.Hidden("hdfClientCode", Request["clientCode"]);
		    <div class="linha-btn">
			    <a type="button" class="btn-primario" href="#" name="btnDelete" id="btnDelete"
                title="excluir cliente" onclick="DeleteRequest($('#hdfRequestId').val(), $('#hdfClientCode').val());" ><span>sim, excluir esta solicitação</span></a> 
                    <a type="button" class="btn-secundario"	href="javascript:;" name="btnCancel" onclick="Modal.Close();" id="btnCancel"
					    title="cancelar exclusão"><span>não excluir</span></a>
		    </div>
     }
<span class="quebrar"></span>
</div>
<span class="quebrar"></span>
<script type="text/javascript">

    function DeleteRequest(requestId, clientCode) {
        $.ajax({
            url: "/Financial/DeleteRedemptionRequest",
            type: "POST",
            dataType: "json",
            data: { hdfRequestId: requestId, hdfClientCode: clientCode },
            success: function (data) {
                if (data.Error == "") {
                    Modal.Close();
                    $("div#divRedemptionRequestFeedback span").html(data.Message);
                    $("div#divRedemptionRequestFeedback").show();
                    fnSearch($('#redemptionRequestFilterContent'));
                }
                else {
                    Modal.Close();
                    $("#feedbackError").html(data.Error);
                    $("#feedbackError").show();
                }

                ReloadPending();
            }
        });
    }

</script>

brpartners/web/Views/Financial/RedemptionRequestEdit.cshtml
@{
    Layout = null;
}
@using QX3.Portal.Contracts.DataContracts
@using QX3.Portal.WebSite.Helper
@model RedemptionRequestItem
<script src="@Url.Content("~/Scripts/jQuery/meioMask/jquery.meio.mask.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jQuery/validate/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Views/Financial/RedemptionRequestEdit.js?new=" + DateTime.Now.Ticks.ToString())" type="text/javascript"></script>
@using (Html.BeginForm("RedemptionRequestEdit", "Financial", FormMethod.Post, new { @id = "frmRedemptionRequestEdit" }))
{
    string title = Model.Client == null ? "Solicitar Resgate" : "Editar Resgate";
    string btnName = Model.Client == null ? "solicitar resgate" : "editar resgate";
    
    <h2>@title</h2>
    <div class="conteudo solicitar-resgate" id="divRedemptionRequestEdit">
        <div id="feedbackRequestError" class="erro" style="display: none;">
        </div>
        <span class="quebrar"></span>
        @Html.Partial("FeedbackError", new QX3.Portal.WebSite.Models.Error { Message = TempData["ErrorMessage"] == null ? string.Empty : TempData["ErrorMessage"].ToString(), DisplayMode = TempData["ErrorMessage"] != null ? "block" : "none", IsList = true })
        
        <table class="tabela-zerada" cellpadding="0" cellspacing="0">
            <tbody>
            <tr>
                <td width="350px" height="282px">
                    <div class="frm-solicitar-resgate">
                    <span class="quebrar"></span>
                    <div class="linha-frm campo-condigo-cliente">
                        <label>Código do Cliente</label>
                        @Html.TextBox("txtClientName", Model.Client != null ? Model.Client.Value : "", new { @maxlength = 30 })
                        @Html.Hidden("hdfClientCode", Model.Client != null ? Model.Client.Value : "0")
                        @Html.Hidden("hdfRequestId", Model.ID)
                    </div>
                    @{ string titleClientName = Model.Client != null ? Model.Client.Description : "";}
                    <span id="lblClientName" class="apoio" title='@titleClientName'>@(Model.Client != null ? Model.Client.Description : "")</span>
                    <span class="quebrar"></span>
                    <div class="linha-frm conta">
                        <label>Conta</label>
                        <select id="ddlBankAccounts" name="ddlBankAccounts">
                            <option value=""></option>
                        </select>
                        @Html.Hidden("hdfBankAccountNumber", Model.Client != null ? Model.BankAccount.AccountNumber : "")
                    </div>
                    <span class="quebrar"></span>
                    <div class="linha-frm">
                        <label id="lblAmount">Valor</label>
                        @Html.TextBox("txtAmount", Model.Client != null ? Model.RedemptionValue.ToString("N2") : "", new { @maxlength = 30, @disabled = "disabled" })
                    </div>
                    <div class="linha-frm total">
                        <input type="checkbox" id="chkTotalD0" />
                        <label id="lblTotalD0">Total D0</label>
                    </div>
                    <span class="quebrar"></span>
                    </div>
                </td>
                <td width="400px" height="282px">
                    <div class="tabela-solicitar-resgate" id="divBalanceContent">
                    <table cellpadding="0" cellspacing="0" class="classificar" width="100%">
                        <thead>
                            <tr>
                                <th class="zerada" width="80px">
                                </th>
                                <th width="79px" class="esquerda">
                                    D0
                                </th>
                                <th width="79px" class="esquerda">
                                    D1
                                </th>
                                <th width="79px" class="esquerda">
                                    D2
                                </th>
                                <th width="79px" class="esquerda">
                                    D3
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr class="odd">
                                <td class="zerada" width="80px">
                                </td>
                                <td class="direita">
                                    <span id="lblBalanceD0"></span>
                                </td>
                                <td class="direita">
                                    <span id="lblBalanceD1"></span>
                                </td>
                                <td class="direita">
                                    <span id="lblBalanceD2"></span>
                                </td>
                                <td class="direita">
                                    <span id="lblBalanceD3"></span>
                                </td>
                            </tr>
                            <tr class="even">
                                <td width="90px">
                                    <div style="width:90px;">Após Resgate ></div>
                                </td>
                                <td class="direita">
                                    <span id="lblRedemptionD0"></span>
                                </td>
                                <td class="direita">
                                    <span id="lblRedemptionD1"></span>
                                </td>
                                <td class="direita">
                                    <span id="lblRedemptionD2"></span>
                                </td>
                                <td class="direita">
                                    <span id="lblRedemptionD3"></span>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <table cellpadding="0" cellspacing="0" class="classificar" width="100%">
                        <thead>
                            <tr>
                                <th class="zerada" width="80px">
                                </th>
                                <th width="176px" class="esquerda">
                                    Projetado (D1+D2+D3)
                                </th>
                                <th width="176px" class="esquerda">
                                    Total (Projetado +D0)
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr class="odd">
                                <td class="zerada" width="80px">
                                </td>
                                <td class="direita">
                                    <span id="lblBalanceProjetado"></span>
                                </td>
                                <td class="direita">
                                    <span id="lblBalanceTotal"></span>
                                </td>
                            </tr>
                            <tr class="even">
                                <td width="90px">
                                    <div style="width:90px;">Após Resgate ></div>
                                </td>
                                <td class="direita">
                                    <span id="lblRedemptionProjetado"></span>
                                </td>
                                <td class="direita">
                                    <span id="lblRedemptionTotal"></span>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    @Html.Hidden("hdfBalanceD0", "")
                    </div>
                </td>
            <tr>
            </tbody>
        </table>

        <div class="linha-btn" style="float: left; margin: 10px 0 0 0;" id="divSave">
            <a href="javascript:;" class="btn-padrao" id="lnkSave"><span>@btnName</span></a>
        </div>
        @Html.Hidden("hdfSave", "false")
    </div>

}