brpartners/web/Controllers/BMFController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QX3.Portal.WebSite.Models.Channel;
//using QX3.Portal.WebSite.BMFService;
using QX3.Portal.Contracts.DataContracts;
using QX3.Portal.WebSite.Helper;
using QX3.Portal.WebSite.Models;
using QX3.Portal.WebSite.OtherService;
using QX3.Spinnex.Common.Services.Logging;

namespace QX3.Portal.WebSite.Controllers
{
    public class BMFController : FileController
    {

        //#region FinancialStatement - Extrato Financeiro

        //public ActionResult FinancialStatement()
        //{
        //    return View();
        //}

        //public ActionResult EditEmailModel()
        //{
        //    return View();
        //}

        //#endregion

        //#region Relatório de Corretagem

        //[AccessControlAuthorize]
        //public ActionResult BrokerageReport() 
        //{
        //    using (var service = ChannelProviderFactory<IOtherContractChannel>.Create("OtherClassName").GetChannel().CreateChannel())
        //    {
        //        var tradingDates = service.GetTradingDates().Result;
        //        ViewBag.TradingDate = tradingDates == null ? DateTime.Now.ToShortDateString() : tradingDates.Select(t=>t.Value).FirstOrDefault();
        //    }

        //    return View();
        //}

        //[HttpPost]
        //public ActionResult BrokerageReportFilter(string txtClients, string txtAssessors, DateTime? txtStartDate, DateTime? txtEndDate) 
        //{
        //    using (var service = ChannelProviderFactory<IBMFContractChannel>.Create("BMFClassName").GetChannel().CreateChannel()) 
        //    {
        //        BrokerageReportFilter filter = new BrokerageReportFilter()
        //        {
        //            AssessorFilter = String.IsNullOrEmpty(txtAssessors) ? "" : new MarketHelper().GetAssessorsRangesToFilter(txtAssessors),
        //            ClientFilter = new MarketHelper().GetClientsRangesToFilter(txtClients),
        //            InitialRequest = txtStartDate,
        //            FinalRequest = txtEndDate,
        //            UserID = CommonHelper.GetLoggedUserGroupId()
        //        };

        //        var model = new BrokerageTransferInfo();

        //        model.BMFInfo = service.LoadBMFBrokerageReport(filter).Result;
        //        model.BovespaInfo = service.LoadBovespaBrokerageReport(filter).Result;

        //        /*Filtrar clientes*/

        //        var clientList = 
        //            (model.BMFInfo != null) 
        //            ? (model.BovespaInfo != null)
        //                ? model.BMFInfo.Select(a => a.ClientCode).Distinct().Union(model.BovespaInfo.Select(a => a.ClientCode).Distinct()).OrderBy(a => a).ToArray()
        //                : model.BMFInfo.Select(a => a.ClientCode).Distinct().OrderBy(a => a).ToArray()
        //            : (model.BovespaInfo != null)
        //                ? model.BovespaInfo.Select(a => a.ClientCode).Distinct().OrderBy(a => a).ToArray()
        //                : null;

        //        Session["clientList"] = clientList;
        //        Session["modelList"] = model;

        //        if (clientList != null && clientList.Count() > 1)
        //            ViewBag.NextClient = 1;

        //        if (clientList != null && clientList.Count() > 0) 
        //        {
        //            using (var otherService = ChannelProviderFactory<IOtherContractChannel>.Create("OtherClassName").GetChannel().CreateChannel())
        //            {
        //                var assessor = !String.IsNullOrEmpty(txtAssessors) ? new MarketHelper().GetAssessorsRangesToFilter(txtAssessors) : "";
        //                ViewBag.ClientInfo = otherService.LoadClientInformation(clientList[0].ToString(), assessor, CommonHelper.GetLoggedUserGroupId()).Result;
        //            }
        //        }

        //        ViewBag.InfoCount = (clientList != null && clientList.Count() > 0) ? "Exibindo 1 de " + clientList.Count().ToString() : "";

        //        return PartialView("BrokerageReportList"
        //            , clientList == null 
        //                ? new BrokerageTransferInfo() 
        //                : new BrokerageTransferInfo() { 
        //                    BMFInfo = (model.BMFInfo != null) ? model.BMFInfo.Where(a=>a.ClientCode == clientList[0]).ToList() : null, 
        //                    BovespaInfo = (model.BovespaInfo != null) ? model.BovespaInfo.Where(a=>a.ClientCode == clientList[0]).ToList() : null
        //                }
        //            );
        //    }
        //}

        //[HttpPost]
        //public ActionResult BrokerageReportFilter_Paginate(int order)
        //{
        //    var model = (BrokerageTransferInfo)Session["modelList"];
        //    var clientList = (int[])Session["clientList"];

        //    /*Filtrar clientes*/
                       
        //    if (order < clientList.Count() - 1)
        //        ViewBag.NextClient = order + 1;

        //    if (order > 0)
        //        ViewBag.PreviousClient = order - 1;

        //    if (clientList.Count() > 1)
        //    {
        //        using (var otherService = ChannelProviderFactory<IOtherContractChannel>.Create("OtherClassName").GetChannel().CreateChannel())
        //        {
        //            ViewBag.ClientInfo = otherService.LoadClientInformation(clientList[order].ToString(), "", CommonHelper.GetLoggedUserGroupId()).Result;
        //        }
        //    }

        //    ViewBag.InfoCount = (clientList != null && clientList.Count() > 0) ? "Exibindo " + (order + 1).ToString()  + " de " + clientList.Count().ToString() : "";

        //    return PartialView("BrokerageReportList"
        //        , clientList == null
        //            ? new BrokerageTransferInfo()
        //            : new BrokerageTransferInfo()
        //            {
        //                BMFInfo = (model.BMFInfo != null) ? model.BMFInfo.Where(a => a.ClientCode == clientList[order]).ToList() : null,
        //                BovespaInfo = (model.BovespaInfo != null) ? model.BovespaInfo.Where(a => a.ClientCode == clientList[order]).ToList() : null
        //            }
        //        );
                
        //}

        //public ActionResult BrokerageReportToFile(bool isPdf)
        //{
        //    List<CustodyTransfer> currentList = new List<CustodyTransfer>();
        //    try
        //    {
        //        if (Session["modelList"] != null && Session["clientList"] != null)
        //        {
        //            var model = (BrokerageTransferInfo)Session["modelList"];
        //            var clientList = (int[])Session["clientList"];
                                        

        //            string fileName = string.Format("relatoriocorretagem_{0}.{1}", DateTime.Now.ToString("dd-MM-yyyy"), isPdf ? "pdf" : "xls");

        //            List<CPClientInformation> clientInfo = new List<CPClientInformation>();

        //            using (var service = ChannelProviderFactory<IOtherContractChannel>.Create("OtherClassName").GetChannel().CreateChannel()) 
        //            {
        //                foreach (var i in clientList)
        //                {
        //                    var client = service.LoadClientInformation(i.ToString(), "", CommonHelper.GetLoggedUserGroupId()).Result;
        //                    if (client != null) client.ClientCode = i;
        //                    clientInfo.Add(client);
        //                }
        //            }                    

        //            //LogHelper.SaveHistoryLog("BMF.BrokerageTransfer", new HistoryData { Action = "Exportar", OldData = string.Empty, NewData = JsonConvert.SerializeObject(currentList) });

        //            return isPdf ? ViewBrokerageReportPdf(model, clientList.ToList(), clientInfo, true, fileName) : ViewBrokerageReportExcel(model, clientList.ToList(), clientInfo, true, fileName);
                    
        //            //return ViewBrokerageTransferExcel(model, clientList.ToList(), clientInfo, true, fileName);
        //        }

        //        TempData["ErrorMessage"] = "Não há dados para o relatório.";
        //        return this.RedirectToAction("BrokerageTransfer"); 
        //    }
        //    catch (Exception ex)
        //    {
        //        LogManager.WriteError(ex);
        //        TempData["ErrorMessage"] = "Ocorreu um erro ao gerar relatório.";
        //        return this.RedirectToAction("BrokerageTransfer");
        //    }

        //}

        //#endregion

        //#region Faixa de Corretagem

        //public ActionResult BrokerageRange() 
        //{
        //    return View();
        //}

        //public ActionResult BrokerageRangeFilter(FormCollection form) 
        //{ 
        //    BrokerageRange result = null;

        //    BrokerageRangeFilter filter = new BrokerageRangeFilter()
        //    {
        //        ClientFilter = new MarketHelper().GetClientsRangesToFilter(form["txtClientFilter"]),
        //        AssessorFilter = new MarketHelper().GetAssessorsRangesToFilter(form["txtAssessorFilter"]),
        //        UserID = CommonHelper.GetLoggedUserGroupId()
        //    };

        //    FilterOptions options = new FilterOptions()
        //    {
        //        InitRow = Convert.ToInt32(form["DisplayStart"]),
        //        FinalRow = 1,
        //        SortColumn = 1,
        //        SortDirection = "asc",
        //        AllRecords = false
        //    };

        //    using (var service = ChannelProviderFactory<IBMFContractChannel>.Create("BMFClassName").GetChannel().CreateChannel()) 
        //    {
        //        bool hasAnterior, hasPosterior = false;
        //        var response = service.LoadBrokerageRange(out hasAnterior, out hasPosterior, filter, options);
        //        result = response.Result;

brpartners/web/Views/BMF/BrokerageRange.cshtml
@{
    ViewBag.Title = "BrokerageRange";
}

@using QX3.Portal.WebSite.Helper;

<script src="@Url.Content("~/Scripts/jQuery/ui/jquery-ui-1.8.16.custom.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jQuery/meioMask/jquery.meio.mask.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jQuery/ui/jquery.ui.datepicker-pt-BR.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Helpers/jquery.qtip-1.0.0-rc3.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jQuery/jquery.form/jquery.form.js")" type="text/javascript"></script>

<script src="@Url.Content("~/Scripts/Helpers/CommonHelper.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Views/BMF/BrokerageRange.js")" type="text/javascript"></script>

<div class="ferramentas acoes assessores" id="dvExportar" style="display:none;">

	<div><span>Exportar:</span> 
  
		<a id="lnkExcel" class="ico-xls" href="javascript:void(0)">Excel</a>
  
		<a id="lnkPdf" class="ico-pdf" href="javascript:void(0)">PDF</a>
  
	</div>
</div>
@Html.Partial("BrokerageRangeFilter")
@Html.Partial("FeedbackError", new QX3.Portal.WebSite.Models.Error { Message = TempData["ErrorMessage"] == null ? string.Empty : TempData["ErrorMessage"].ToString(), DisplayMode = TempData["ErrorMessage"] != null ? "block" : "none" })
@{var feedbackDisplay = (TempData["Success"] != null) ? "block" : "none";}
<div id="feedback" class="sucesso-flutuante" style='display:@feedbackDisplay;'>
    <span>@(TempData["SuccessMessage"] ?? "")</span><a href="#" class="lnk-fechar" onclick="$('#feedback').slideToggle();"
        id="closeFeedback">fechar</a>
</div>

<div id="emptyArea" class="sem-resultado" style="display: none;">
</div>

<div id="pesquisa" class="sem-resultado" style="margin: 0px;">
Faça uma pesquisa.
</div>

<div id="loadingArea" style="display: none; text-align: center;">
    <img src="../../img/preloadercinza.gif" alt="carregando consulta" />
</div>

<div id="table-client-area" style="display: none;clear:left;">

</div>

brpartners/web/Views/BMF/BrokerageRangeDetails.cshtml
@{
    ViewBag.Title = "BrokerageRangeDetails";
    Layout = null;
}

@using QX3.Portal.Contracts.DataContracts
@model List<BrokerageBMF>
@if (Model != null)
{
<table cellspacing="0" cellpadding="0" class="secundaria" width="55%">
    <thead>
        <tr>
            <th>Vencimento (mês)</th>
            <th>Faixa de Contrato (R$)</th>
            <th>Normal</th>
            <th>Day Trade</th>
        </tr>
    </thead>
    <tbody>
           @foreach (var i in Model)
           { 
                <tr>
                    <td>-</td>
                    <td>-</td>
                    <td class="direita">@i.NormalOperationRate.Value.ToString("N2")</td>
                    <td class="direita">@i.DayTradeRate.Value.ToString("N2")</td>
                </tr>
           } 
    </tbody>
</table>
}

brpartners/web/Views/BMF/BrokerageRangeFilter.cshtml
<script src="@Url.Content("~/Scripts/jQuery/ui/jquery-ui-1.8.16.custom.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Helpers/ValidateHelper.js")" type="text/javascript"></script>

<div class="filtro-padrao">
    <div class="topo" id="BrokerageRangeFilter">
		        Filtrar por
    </div>
	<div class="conteudo" id="BrokerageRangeContent" style="display:none;">
        <span class="quebrar"></span>
        <div id="filterFeedbackError" class="erro" style="display: none;"></div>
		    <div class="linha-frm">
			    <label>Assessor</label>
                @Html.TextBox("txtAssessorFilter")
		    </div>
		    <div class="linha-frm">
			    <label>Cliente</label>
                @Html.TextBox("txtClientFilter")
		    </div>
            <div class="linha-frm">
			    <label>Corretora de Repasse</label>
                @Html.TextBox("txtBrokerage")
		    </div>
            <div class="linha-frm">
			    <label>Atividade</label>
                <select id="ddlType" name="ddlType">
                    <option value="0">Todos</option>
                    <option value="1">Bovespa</option>
                    <option value="2">BM&F</option>
                </select>
		    </div>
            <div class="linha-frm">
			    <label>Mercado</label>
                <select id="ddlMarketType" name="ddlMarketType">
                    <option value="0">Todos</option>
                </select>
		    </div>
            @Html.Hidden("DisplayStart", 0)
		    <div class="linha-btn">
			    <a class="btn-padrao" href="javascript:;" id="lnkSubmitBrokerageRangeFilter"><span>Listar Clientes</span></a>
		    </div>
		    <span class="quebrar"></span>
	    </div>
  </div>

brpartners/web/Views/BMF/BrokerageRangeList.cshtml
@{
    ViewBag.Title = "BrokerageRangeList";
    Layout = null;
}
@using QX3.Portal.Contracts.DataContracts
@model BrokerageRange      

@if (Model != null)
{     
<div class="caixa-cabecalho-lista" id="tableArea" style="width: 100%;">
    <div class="navegacao-tabela">
        <div class="navegacao">
            @if (ViewBag.HasAnterior)
            { <a id="lnkPreviousClientTop" class="lnk-anterior" href="javascript:;" rel="@ViewBag.AnteriorValue">Cliente Anterior</a> }
            @if (ViewBag.HasPosterior)
            { <a id="lnkNextClientTop" class="lnk-proximo" href="javascript:;" rel="@ViewBag.PosteriorValue">Próximo Cliente</a> }
        </div>
        @if (ViewBag.Counter != null)
        { <span id="lblClientCounterTop">@ViewBag.Counter</span> }
    </div>
    <span class="quebrar"></span>
    <div class="cabecalho-grid garantias">
        <div class="etiqueta">
            <h2 id="lblClientNameSpan">@Model.ClientCode - @Model.ClientName</h2>
            <span class="quebrar"></span>
            <div class="bloco">
                <span id="lblAssessor">@Model.AssessorName</span>
            </div>
        </div>
        <span class="quebrar"></span>
    </div>
    <span class="quebrar"></span>
    <div class="area-resultado" style="display: block;">
        @{
        var bovespa = (List<BrokerageBovespa>)Model.Bovespa;  
        }
        @if (bovespa != null && bovespa.Count > 0)
        {
            <table cellpadding="0" width="480px" cellspacing="0" border="0" id="tblBovespaList" class="classificar">
                <thead>
                    <tr class="primario">
                        <th colspan="3">Bovespa</th>
                    </tr>
                    <tr class="secundario">
                        <th>Mercado</th>
                        <th>Normal</th>
                        <th>Day Trade</th>
                    </tr>
                </thead>
                <tbody>
                @foreach (var i in bovespa)
                { 
                    <tr>
                        <td>@i.MarketType</td>
                        <td class="direita">@(i.NormalOperationRate.HasValue ? i.NormalOperationRate.Value.ToString("N2") : "-")</td>
                        <td class="direita">@(i.DayTradeRate.HasValue ? i.DayTradeRate.Value.ToString("N2") : "-")</td>
                    </tr>
                }
                </tbody>
            </table>
            <span class="quebrar"></span>
        }

        <div id="table-bmf-area">
            <table cellpadding="0" width="970px" cellspacing="0" border="0" id="tblBMFList" class="classificar">
                <thead>
                    <tr class="primario">
                        <th colspan="6">BM&F</th>
                    </tr>
                    <tr class="secundario">
                        <th>
                            Ativo
                        </th>
                        <th>
                            Contratos
                        </th>
                        <th>
                            Mercado
                        </th>
                        <th>
                            Normal
                        </th>
                        <th>
                            Day Trade
                        </th>
                        <th>&#160;</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
    <span class="quebrar"></span>
</div>
}
else
{ 
    <div class="alerta">Nenhum cliente encontrado.</div>
}

brpartners/web/Views/BMF/BrokerageReport.cshtml
@{
    ViewBag.Title = "BrokerageTransfer";
    var feedbackDisplay = (TempData["Success"] != null) ? "block" : "none";
    string displayErrorMode = TempData["ErrorMessage"] != null ? "block" : "none";
}

<script src="@Url.Content("~/Scripts/jQuery/ui/jquery-ui-1.8.16.custom.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jQuery/meioMask/jquery.meio.mask.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jQuery/ui/jquery.ui.datepicker-pt-BR.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Helpers/jquery.qtip-1.0.0-rc3.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Helpers/ValidateHelper.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jQuery/jquery.format-1.2/jquery.format-1.2.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jQuery/DateJS/date-pt-BR.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Views/BMF/BrokerageReportFilter.js")" type="text/javascript"></script>


<div id="divFeedback" class="sucesso-flutuante" style='display:@feedbackDisplay;'>
    <span>@(TempData["SuccessMessage"] ?? "")</span><a href="javascript:void(0);" class="lnk-fechar" onclick="$('#divFeedback').slideToggle();" id="closeFeedback">fechar</a>
</div>
	
@Html.Partial("BrokerageReportFilter")
    
<span class="quebrar"></span>

<div id="feedbackError" class="erro" style='display:@displayErrorMode;'>@TempData["ErrorMessage"]</div>
    
<div id="emptyArea" class="sem-resultado" style="display:none; margin-bottom:20px; margin-top:20px;">
</div>

<div id="pesquisa" class="sem-resultado" margin-bottom:20px; margin-top:20px;">
    Faça uma pesquisa.
</div>

<div id="loadingArea" style="display:none; text-align: center;">
    <img src="../../img/preloadercinza.gif" alt="carregando consulta" />
</div>

<div class="area-resultado relatorio-corretagem" id="tableArea" style="display:none;">

        
</div>

brpartners/web/Views/BMF/BrokerageReportFilter.cshtml
<div class="filtro-padrao">
    <div id="BrokerageTransferFilter" class="topo">
        Filtrar por
    </div>
    <div id="BrokerageTransferFilterContent" class="conteudo" style="display: none;">
        @using (Html.BeginForm())
        {
            <div id="filterFeedbackError" class="erro" style="display: none;"></div>
            <span class="quebrar"></span>
            <div class="linha-frm">
                <label>Assessor</label>
                    @Html.TextBox("txtAssessors")
            </div>
            <div class="linha-frm">
                <label>Cliente</label>
                    @Html.TextBox("txtClients")
            </div>
            <div class="linha-frm conjugado">
                <label>Período</label>
                <div>
                    @Html.TextBox("txtStartDate", (string)ViewBag.TradingDate, new { @id = "txtStartDate", @maxlength = "10" })
                    @Html.TextBox("txtEndDate", (string)ViewBag.TradingDate, new { @id = "txtEndDate", @maxlength = "10" })
                </div>
            </div>
            <div class="linha-btn">
                <a href="javascript:;" class="btn-padrao" id="btnSearch"><span>listar relatório</span></a>
            </div>
            <span class="quebrar"></span>
        }
    </div>
</div>

brpartners/web/Views/BMF/BrokerageReportList.cshtml
@{
    ViewBag.Title = "";
    Layout = null;
    int? nextClient = null, previousClient = null; 
}
@using QX3.Portal.Contracts.DataContracts
@model BrokerageTransferInfo

@if (Model.BMFInfo == null && Model.BovespaInfo == null)
{ 
    <div class="sem-resultado">Não foram encontrados clientes de acordo com o filtro.</div>
}
else
{ 
    if (ViewBag.NextClient != null) { nextClient = (int)ViewBag.NextClient; }
    if (ViewBag.PreviousClient != null) { previousClient = (int)ViewBag.PreviousClient; }
     
    <div class="ferramentas acoes assessores">
        <div>
            <span id="dvExportar">Exportar:</span> 
            <a id="lnkExcel" class="ico-xls" href='@Url.Action("BrokerageReportToFile", "BMF", new { isPdf = false })'>Excel</a>
  
            <a id="lnkPdf" class="ico-pdf" href='@Url.Action("BrokerageReportToFile", "BMF", new { isPdf = true })'>PDF</a>
        </div>
    </div>
    
    <div class="navegacao-tabela">
        <div class="navegacao">
            @if (previousClient.HasValue)
            {
                <a id="lnkPreviousClientTop" rel='@previousClient.Value' class="lnk-anterior" href="javascript:;">Cliente Anterior</a> 
            }
            @if (nextClient.HasValue)
            {
                <a id="lnkNextClientTop" rel='@nextClient.Value' class="lnk-proximo" href="javascript:;">Próximo Cliente</a>
            }
            @ViewBag.InfoCount
        </div>
        <span id="lblClientCounterTop"></span>
    </div>
    <span class="quebrar"></span>
    
            var clientInfo = (CPClientInformation)ViewBag.ClientInfo;

            if (clientInfo != null)
            {
        <div class="cabecalho-grid garantias">
            <div class="etiqueta">
                <h2 id="lblClientNameSpan">@clientInfo.Client.Value - @clientInfo.Client.Description
                </h2>
                <span class="quebrar"></span>
                <div class="bloco">
                    <span id="lblAssessor">@clientInfo.AssessorName</span>
                </div>
            </div>
            <span class="quebrar"></span>
        </div>
            }
	
    <span class="quebrar"></span>

            if (Model.BMFInfo != null && Model.BMFInfo.Count > 0)
            {
        <h3>BM&F</h3>
        <table cellspacing="0" cellpadding="0" border="0" class="classificar" id="BMFList">
            <thead>
                <tr class="primario">
                    <th rowspan="2">
                        Corretora
                    </th>
                    <th rowspan="2">
                        Produto
                    </th>
                    <th rowspan="2">
                        Corretagem Bruta
                    </th>
                    <th colspan="2">
                        Repasse de Corretagem
                    </th>
                    <th rowspan="2" class="ultimo">
                        Receita em R$ (Bruta - Repasse)
                    </th>
                </tr>
                <tr class="secundario">
                    <th>
                        R$
                    </th>
                    <th>
                        %
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var bmf in Model.BMFInfo)
                {
                    <tr>
                        <td>@bmf.Broker</td>
                        <td>@bmf.Product</td>
                        <td class='@((bmf.GrossBrokerage.HasValue) ? bmf.GrossBrokerage.Value <= 0 ? "negativo" : "" : "") direita'>@((bmf.GrossBrokerage.HasValue) ? bmf.GrossBrokerage.Value.ToString("N2") : "")</td>
                        <td class='@((bmf.TransferValue.HasValue) ? bmf.TransferValue.Value <= 0 ? "negativo" : "" : "") direita'>@((bmf.TransferValue.HasValue) ? bmf.TransferValue.Value.ToString("N2") : "")</td>
                        <td class='@((bmf.TransferPercentual.HasValue) ? bmf.TransferPercentual.Value <= 0 ? "negativo" : "" : "") direita'>@((bmf.TransferPercentual.HasValue) ? bmf.TransferPercentual.Value.ToString("N2") : "")</td>
                        <td class='@((bmf.Revenue.HasValue) ? bmf.Revenue.Value <= 0 ? "negativo" : "" : "") direita'>@((bmf.Revenue.HasValue) ? bmf.Revenue.Value.ToString("N2") : "")</td>
                    </tr>
                }
            </tbody>
            <tfoot class="resultado">
                <tr>
                    <td colspan="2" class="zerada total">Total:</td>
                    <td class='@((Model.BMFInfo.Sum(a => a.GrossBrokerage).HasValue) ? Model.BMFInfo.Sum(a => a.GrossBrokerage).Value <= 0 ? "negativo" : "" : "") direita'>@((Model.BMFInfo.Sum(a => a.GrossBrokerage).HasValue) ? Model.BMFInfo.Sum(a => a.GrossBrokerage).Value.ToString("N2") : "")</td>
                    <td class='@((Model.BMFInfo.Sum(a => a.TransferValue).HasValue) ? Model.BMFInfo.Sum(a => a.TransferValue).Value <= 0 ? "negativo" : "" : "") direita'>@((Model.BMFInfo.Sum(a => a.TransferValue).HasValue) ? Model.BMFInfo.Sum(a => a.TransferValue).Value.ToString("N2") : "")</td>
                    <td class='@((Model.BMFInfo.Sum(a => a.TransferPercentual).HasValue) ? Model.BMFInfo.Sum(a => a.TransferPercentual).Value <= 0 ? "negativo" : "" : "") direita'>@((Model.BMFInfo.Sum(a => a.TransferPercentual).HasValue) ? Model.BMFInfo.Sum(a => a.TransferPercentual).Value.ToString("N2") : "")</td>
                    <td class='@((Model.BMFInfo.Sum(a => a.Revenue).HasValue) ? Model.BMFInfo.Sum(a => a.Revenue).Value <= 0 ? "negativo" : "" : "") direita'>@((Model.BMFInfo.Sum(a => a.Revenue).HasValue) ? Model.BMFInfo.Sum(a => a.Revenue).Value.ToString("N2") : "")</td>
                </tr>
            </tfoot>
        </table>
    
        <span class="quebrar"></span>
            }

            if (Model.BovespaInfo != null && Model.BovespaInfo.Count > 0)
            { 
        <h3>Bovespa</h3>
        <table cellspacing="0" cellpadding="0" border="0" class="classificar" id="BovespaList">
            <thead>
                <tr class="primario">
                    <th >
                        Corretagem Bruta (R$)
                    </th>
                    <th >
                        Corretagem Líquida (R$)
                    </th>
                    <th >
                        Desconto em R$ (Bruta - Líquida)
                    </th>
                </tr>
            </thead>
            <tbody class="resultado">
                @foreach (var bovespa in Model.BovespaInfo)
                {
                    <tr>
                        <td class='@((bovespa.GrossBrokerage.HasValue) ? bovespa.GrossBrokerage.Value <= 0 ? "negativo" : "" : "") direita'>@((bovespa.GrossBrokerage.HasValue) ? bovespa.GrossBrokerage.Value.ToString("N2") : "")</td>
                        <td class='@((bovespa.NetBrokerage.HasValue) ? bovespa.NetBrokerage.Value <= 0 ? "negativo" : "" : "") direita'>@((bovespa.NetBrokerage.HasValue) ? bovespa.NetBrokerage.Value.ToString("N2") : "")</td>
                        <td class='@((bovespa.DiscountValue.HasValue) ? bovespa.DiscountValue.Value <= 0 ? "negativo" : "" : "") direita'>@((bovespa.DiscountValue.HasValue) ? bovespa.DiscountValue.Value.ToString("N2") : "")</td>
                    </tr>
                }
            </tbody>
        </table>
    }
}